### ISSUE TITLE
Case works + Vial firmware

### ISSUE THREAD

**Issue by articnova** [mkylama/disorder30#2]
Hey, not sure how else to contact regarding this but I've used the 3d files for printing the case and can confirm it works.

With regards to the firmware files, I had to add a config.h file with the settings as I couldn't build a vial hex using the files in the vial folder as is. Had to do this as I needed to use another pin due to a lifted pad on my microcontroller.

**Comment by articnova** [comment]
Opened and closed - Just to give update for mkylama

**Comment by mkylama** [comment]
Thank you for letting me know. Pushed the missing vial config.h file to repo.
Hope you enjoy the board as much as it's even possible :D
